const loadingTitles = [
  { title: "Inception", category: "viewed" },
  { title: "Parasite", category: "2watch" },
  { title: "The Dark Knight", category: "viewed" },
  { title: "Interstellar", category: "2watch" },
  { title: "The Grand Budapest Hotel", category: "viewed" },
  { title: "Whiplash", category: "2watch" },
  { title: "Joker", category: "viewed" },
  { title: "Everything Everywhere All at Once", category: "2watch" },
  { title: "Oppenheimer", category: "viewed" },
  { title: "Dune: Part One", category: "2watch" },
  { title: "Avatar", category: "viewed" },
  { title: "The Matrix", category: "2watch" },
  { title: "Pulp Fiction", category: "viewed" },
  { title: "Gladiator", category: "2watch" },
  { title: "The Social Network", category: "viewed" },
  { title: "Breaking Bad", category: "viewed" },
  { title: "Game of Thrones", category: "2watch" },
  { title: "The Office", category: "viewed" },
  { title: "Stranger Things", category: "2watch" },
  { title: "The Crown", category: "viewed" },
  { title: "The Mandalorian", category: "2watch" },
  { title: "Better Call Saul", category: "viewed" },
  { title: "The Witcher", category: "2watch" },
  { title: "The Boys", category: "viewed" },
  { title: "Succession", category: "2watch" },
  { title: "Black Mirror", category: "viewed" },
  { title: "Sherlock", category: "2watch" },
  { title: "Fargo", category: "viewed" },
  { title: "Chernobyl", category: "2watch" },
  { title: "Westworld", category: "viewed" },
  { title: "The Last of Us", category: "viewed" },
  { title: "Dune: Part Two", category: "2watch" },
  { title: "Severance", category: "2watch" },
  { title: "House of the Dragon", category: "viewed" },
  { title: "The Bear", category: "2watch" }
];

export default loadingTitles;   